# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe_Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('amount', models.CharField(max_length=30)),
                ('ingre_name', models.CharField(max_length=30)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.Ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('img_review', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('is_timer', models.BooleanField(default=False)),
                ('timer_timer', models.PositiveIntegerField(default=0)),
                ('img_step', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeStepComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('recipe_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.RecipeStep')),
            ],
        ),
        migrations.CreateModel(
            name='RecipeTitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('bookmark_count', models.PositiveIntegerField(default=0)),
                ('rate_sum', models.PositiveIntegerField(default=0)),
                ('img_recipe', models.ImageField(upload_to='')),
                ('cal_sum', models.PositiveIntegerField(default=0)),
                ('ingredient', models.ManyToManyField(related_name='Recipe_Ingredient', through='recipe.Recipe_Ingredient', to='ingredient.Ingredient')),
            ],
        ),
        migrations.AddField(
            model_name='recipestep',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.RecipeTitle'),
        ),
        migrations.AddField(
            model_name='recipereview',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.RecipeTitle'),
        ),
        migrations.AddField(
            model_name='recipe_ingredient',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipe.RecipeTitle'),
        ),
    ]
