# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeTitle',
            new_name='Recipe',
        ),
    ]
