# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickyuser',
            options={},
        ),
        migrations.AlterModelManagers(
            name='pickyuser',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='profile_content',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='profile_image',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='sns_username',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='pickyuser',
            name='username',
        ),
        migrations.AddField(
            model_name='pickyuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pickyuser',
            name='email',
            field=models.EmailField(max_length=100, unique=True, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='pickyuser',
            name='id_type',
            field=models.CharField(default='d', max_length=1),
        ),
        migrations.AlterField(
            model_name='pickyuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pickyuser',
            name='nickname',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
