# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_auto_20170801_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickyuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
