# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_pickyuser_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickyuser',
            name='is_staff',
        ),
    ]
