# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 09:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=256)),
                ('unit', models.CharField(max_length=30)),
                ('cal', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
